server:
  port: 8070
spring:
  application:
    name: result-service
  data:
    mongodb:
      uri: mongodb://admin:pass@localhost:27017
      database: results
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    consul:
      discovery:
        enabled: true
      host: localhost
      port: 8500

access-token-secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret